account_id = ""
compatibility_date = "2022-05-30"
name = "pionta-park"
route = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
workers_dev = true
zone_id = ""

[site]
bucket = "out"
entry-point = "./"
